### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by dapetcu21** [krtx/lua-parser#1]
Hi!

I'm considering to use your grammars for a rewrite of my [dapetcu21/atom-autocomplete-lua](https://github.com/dapetcu21/atom-autocomplete-lua), but since there is no license on this repo, I can't assume permission to use your code.

If that's ok, can you please add a license to the repo? Maybe [MIT](https://choosealicense.com/licenses/mit/) would be a good start?

**Comment by kinoshita-m** [comment]
@dapetcu21 
Sorry for the late reply. I added MIT License (0453abbf9048daf827a8a37457d8e08daeca5a4c).

**Comment by dapetcu21** [comment]
Thank you 😄
